using System.ComponentModel;
using System.Reflection;
using System.Security.Policy;
using GenericRepository;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using porTIEVserver.Application.Globals;
using porTIEVserver.Domain.Entities.Admin.AppSets;
using porTIEVserver.Domain.Entities.Admin.ToolSets;
using porTIEVserver.Domain.Enums;


namespace porTIEVserver.Infrastructure.Context
{
    internal sealed class AppDbContext : IdentityDbContext<AppUser, IdentityRole<Guid>, Guid>, IUnitOfWork
    {
        public AppDbContext(DbContextOptions options) : base(options)
        {
        }
        #region AppSets
        public DbSet<Firm>                  PT_Firms                { get; set; }
        public DbSet<Menu>                  PT_Menus                { get; set; }
        public DbSet<Rite>                  PT_Rites                { get; set; }
        public DbSet<Role>                  PT_Roles                { get; set; }
        #endregion AppSets
                                            
        #region ToolSets
        public DbSet<BankBranch>            PT_BankBranchs          { get; set; }
        public DbSet<Bank>                  PT_Banks                { get; set; }
        public DbSet<City>                  PT_Cities               { get; set; }
        public DbSet<Country>               PT_Countries            { get; set; }
        public DbSet<StkUnit>               PT_StkUnits             { get; set; }
        public DbSet<StkUnitSet>            PT_StkUnitSets          { get; set; }
        #endregion ToolSets

        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());

            builder.Ignore<IdentityUser<Guid>>();

            builder.Ignore<IdentityUserClaim<Guid>>();
            builder.Ignore<IdentityUserLogin<Guid>>();
            builder.Ignore<IdentityUserToken<Guid>>();
            
            builder.Ignore<IdentityRole<Guid>>();
            builder.Ignore<IdentityRoleClaim<Guid>>();
            builder.Ignore<IdentityUserRole<Guid>>();
            
            /* Firms */
            int FirmRef = 0;
            builder.Entity<Firm>().HasData(
                new Firm() 
                { 
                    Ref = FirmRef + 1,
                    FirmType = FirmTypeEnum.Anonim,
                    Code = "DEMO",
                    Name = "Demo A.Ş.",
                    Desc = "Demo Anonim Şirketi",
                    FullAddress = "",
                    CityCode = "34",
                    CountryCode = "TR",
                    TaxOffice = "",
                    TaxNumber = "1111111111",
                    ImgUrl = "Atam.jpg",
                    CurrencyType = CurrencyTypeEnum.TL,
                    DbServ = Parameters.DbServ,
                    DbName = Parameters.DbName,
                    DbUser = Parameters.DbUser,
                    DbPass = Parameters.DbPass,
                    Active = true,
                    CreatedUser = 1,
                    IsDeleted = false
                }
                );

            /* Roles */
            int RoleRef = 0;
            builder.Entity<Role>().HasData(
                new Role() { Ref = RoleRef+1, Code = "ADM", Name = "Yönetici"    , Active = true, CreatedUser = 1, IsDeleted = false },
                new Role() { Ref = RoleRef+2, Code = "CRG", Name = "Kargo"       , Active = true, CreatedUser = 1, IsDeleted = false },
                new Role() { Ref = RoleRef+3, Code = "CRM", Name = "Satış Öncesi", Active = true, CreatedUser = 1, IsDeleted = false },
                new Role() { Ref = RoleRef+4, Code = "SLS", Name = "Satış"       , Active = true, CreatedUser = 1, IsDeleted = false },
                new Role() { Ref = RoleRef+5, Code = "TRN", Name = "Eğitim"      , Active = true, CreatedUser = 1, IsDeleted = false }
                );

            /* Menus */
            /* Bağımsız Menu Elemanı için 01 ile bitmeli (Anasayfa:1001) */
            /* Akordiyon menu başlık için 00 ile bitmeli (Admin İşlemleri:1100) */
            /* Akordiyon menu satır için ilk iki hane başlık ile aynı olmalı(Admin İşlemleri:1100 / Kullanıcılar:1110) */
            builder.Entity<Menu>().HasData(
                new Menu() { Ref = 1001, Code = "1001", Name = "Ana Sayfa",                      Icon = "fa-solid fa-home",                     AppUrl = "/",                       		    ImgUrl = "fa-home.jpg",                      IsAdmin = true , Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1100, Code = "1100", Name = "Admin İşlemleri",                Icon = "",                                     AppUrl = "/admin",                  		    ImgUrl = "",                                 IsAdmin = true , Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1110, Code = "1110", Name = "Kullanıcılar",                   Icon = "fa-solid fa-user",                     AppUrl = "/admin/users",            		    ImgUrl = "fa-user.jpg",                      IsAdmin = true , Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1120, Code = "1120", Name = "Firmalar",                       Icon = "fa-solid fa-city",                     AppUrl = "/admin/firms",        			    ImgUrl = "fa-city.jpg",                      IsAdmin = true , Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1130, Code = "1130", Name = "Roller",                         Icon = "fa-solid fa-user-group",               AppUrl = "/admin/roles",           			    ImgUrl = "fa-user-group.jpg",                IsAdmin = true , Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1140, Code = "1140", Name = "Menuler",                        Icon = "fa-solid fa-person-circle-check",      AppUrl = "/admin/menus",            		    ImgUrl = "fa-person-circle-check.jpg",       IsAdmin = true , Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1200, Code = "1200", Name = "Genel Tanımlar",                 Icon = "",                                     AppUrl = "/gnrldefines",               		    ImgUrl = "",                                 IsAdmin = true , Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1210, Code = "1210", Name = "Stok Birimleri",                 Icon = "fa-solid fa-users",                    AppUrl = "/gnrldefines/stkunits",      		    ImgUrl = "fa-users.jpg",                     IsAdmin = true , Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1220, Code = "1220", Name = "Stok Birim Setleri",             Icon = "fa-solid fa-boxes-stacked",            AppUrl = "/gnrldefines/stkunitsets",   		    ImgUrl = "fa-boxes-stacked.jpg",             IsAdmin = true , Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1230, Code = "1230", Name = "Ülkeler",                        Icon = "fa-solid fa-map",                      AppUrl = "/gnrldefines/countrys",      		    ImgUrl = "fa-map.jpg",                       IsAdmin = true , Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1240, Code = "1240", Name = "Şehirler",                       Icon = "fa-solid fa-city",                     AppUrl = "/gnrldefines/citys",         		    ImgUrl = "fa-city.jpg",                      IsAdmin = true , Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1250, Code = "1250", Name = "Bankalar",                       Icon = "fa-solid fa-tags",                     AppUrl = "/gnrldefines/banks",         		    ImgUrl = "fa-tags.jpg",                      IsAdmin = true , Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1260, Code = "1260", Name = "Banka Şubeleri",                 Icon = "fa-solid fa-users",                    AppUrl = "/gnrldefines/bankbranchs",   		    ImgUrl = "fa-users.jpg",                     IsAdmin = true , Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1300, Code = "1300", Name = "Firma Tanımları",                Icon = "",                                     AppUrl = "/firmdefines",               		    ImgUrl = "",                                 IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1310, Code = "1310", Name = "Personeller",                    Icon = "fa-solid fa-tags",                     AppUrl = "/firmdefines/personnels",    		    ImgUrl = "fa-tags.jpg",                      IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1320, Code = "1320", Name = "Kasalar",                        Icon = "fa-solid fa-cash-register",            AppUrl = "/firmdefines/cashiers",      		    ImgUrl = "fa-cash-register.jpg",             IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1330, Code = "1330", Name = "Banka Hesapları",                Icon = "fa-solid fa-building-columns",         AppUrl = "/firmdefines/bankaccounts",  		    ImgUrl = "fa-building-columns.jpg",          IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1340, Code = "1340", Name = "Cariler",                        Icon = "fa-solid fa-users",                    AppUrl = "/firmdefines/customers",     		    ImgUrl = "fa-users.jpg",                     IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1350, Code = "1350", Name = "Stoklar",                        Icon = "fa-solid fa-boxes-stacked",            AppUrl = "/firmdefines/products",      		    ImgUrl = "fa-boxes-stacked.jpg",             IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1360, Code = "1360", Name = "Fiyatlar",                       Icon = "fa-solid fa-tags",                     AppUrl = "/firmdefines/prices",        		    ImgUrl = "fa-tags.jpg",                      IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1400, Code = "1400", Name = "Kurs İşlemleri",                 Icon = "",                                     AppUrl = "/eTrainings",               		    ImgUrl = "",                                 IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1410, Code = "1410", Name = "Sınıflar",                       Icon = "fa-solid fa-users",                    AppUrl = "/eTrainings/classrooms",       		ImgUrl = "fa-users.jpg",                     IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1420, Code = "1420", Name = "Kurslar",                        Icon = "fa-solid fa-truck-fast",               AppUrl = "/eTrainings/courses",         		ImgUrl = "fa-truck-fast.jpg",                IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1430, Code = "1430", Name = "Katılımcılar",                   Icon = "fa-solid fa-box-archive",              AppUrl = "/eTrainings/participants",      		ImgUrl = "fa-box-archive.jpg",               IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1440, Code = "1440", Name = "Ortak Firmalar",                 Icon = "fa-solid fa-wallet",                   AppUrl = "/eTrainings/partners",        		ImgUrl = "fa-wallet.jpg",                    IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1450, Code = "1450", Name = "Durum Kodları",                  Icon = "fa-solid fa-upload",                   AppUrl = "/eTrainings/statues",         		ImgUrl = "fa-upload.jpg",                    IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1460, Code = "1460", Name = "Raporlar",                       Icon = "fa-solid fa-print",                    AppUrl = "/eTrainings/reports",         		ImgUrl = "fa-print.jpg",                     IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1500, Code = "1500", Name = "Satış Öncesi",                   Icon = "",                                     AppUrl = "/crm",                       		    ImgUrl = "",                                 IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1510, Code = "1510", Name = "Adaylar",                        Icon = "fa-solid fa-candidate",                AppUrl = "/crm/leads",                 		    ImgUrl = "fa-candidate.jpg",                 IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1520, Code = "1520", Name = "Kişiler",                        Icon = "fa-solid fa-contact",                  AppUrl = "/crm/contacts",              		    ImgUrl = "fa-contact.jpg",                   IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1530, Code = "1530", Name = "Faaliyetler",                    Icon = "fa-solid fa-handshake-angle",          AppUrl = "/crm/crmactions",            		    ImgUrl = "fa-handshake-angle.jpg",           IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1540, Code = "1540", Name = "Teklifler",                      Icon = "fa-solid fa-handshake-angle",          AppUrl = "/crm/crmactions",            		    ImgUrl = "fa-handshake-angle.jpg",           IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1600, Code = "1600", Name = "Satış İşlemleri",                Icon = "",                                     AppUrl = "/sales",                       	    ImgUrl = "",                                 IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1610, Code = "1610", Name = "Siparişler",                     Icon = "fa-solid fa-folder-open",              AppUrl = "/sales/orders",           		    ImgUrl = "fa-folder-open.jpg",               IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1620, Code = "1620", Name = "Sipariş Sevk",                   Icon = "fa-solid fa-truck-arrow-right",        AppUrl = "/sales/despatches",       		    ImgUrl = "fa-truck-arrow-right.jpg",         IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1630, Code = "1630", Name = "Toplu Mal Ayırma",               Icon = "fa-solid fa-basket-shopping",          AppUrl = "/sales/picking ",         		    ImgUrl = "fa-basket-shopping.jpg",           IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1640, Code = "1640", Name = "Mal Teslim",                     Icon = "fa-solid fa-user",                     AppUrl = "/sales/delivery",         		    ImgUrl = "fa-user.jpg",                      IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1700, Code = "1700", Name = "Satın alma İşlemleri",           Icon = "",                                     AppUrl = "/purchase",                    	    ImgUrl = "",                                 IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1710, Code = "1710", Name = "Siparişler",                     Icon = "fa-solid fa-folder-open",              AppUrl = "/purchase/orders",        		    ImgUrl = "fa-folder-open.jpg",               IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1720, Code = "1720", Name = "Mal Kabul",                      Icon = "fa-solid fa-truck-arrow-left",         AppUrl = "/purchase/despatches",    		    ImgUrl = "fa-truck-arrow-left.jpg",          IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1730, Code = "1730", Name = "Kalite kontrol",                 Icon = "fa-solid fa-thumbs-up",                AppUrl = "/purchase/quality ",      		    ImgUrl = "fa-thumbs-up.jpg",                 IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1740, Code = "1740", Name = "Kesin Kabul/Red",                Icon = "fa-solid fa-handshake-simple",         AppUrl = "/purchase/approval",      		    ImgUrl = "fa-handshake-simple.jpg",          IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1800, Code = "1800", Name = "Satış Sonrası",                  Icon = "",                                     AppUrl = "/postsales",                   	    ImgUrl = "",                                 IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1810, Code = "1810", Name = "Sozlesmeler",                    Icon = "fa-solid fa-file-signature",           AppUrl = "/postsales/contracts",         	    ImgUrl = "fa-file-signature.jpg",            IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1820, Code = "1820", Name = "Bakımlar",                       Icon = "fa-solid fa-screwdriver-wrench",       AppUrl = "/postsales/maintains",         	    ImgUrl = "fa-screwdriver-wrench.jpg",        IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1830, Code = "1830", Name = "Görevler",                       Icon = "fa-solid fa-list-check",               AppUrl = "/postsales/tasks",             	    ImgUrl = "fa-list-check.jpg",                IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1900, Code = "1900", Name = "Ambar İşlemleri",                Icon = "fa-solid fa-warehouse",                AppUrl = "/warehouse",                   	    ImgUrl = "fa-warehouse.jpg",                 IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1910, Code = "1910", Name = "Ambar Transfer",                 Icon = "fa-solid fa-cubes-stacked",            AppUrl = "/warehouse/transfers",    		    ImgUrl = "fa-cubes-stacked.jpg",             IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 1920, Code = "1920", Name = "Adres/Raf Değiştirme",           Icon = "fa-solid fa-people-carry-box",         AppUrl = "/warehouse/despatches",   		    ImgUrl = "fa-people-carry-box.jpg",          IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 2000, Code = "2000", Name = "Sayım İşlemleri",                Icon = "",                                     AppUrl = "/inventory",                   	    ImgUrl = "",                                 IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 2010, Code = "2010", Name = "Sayımlar",                       Icon = "fa-solid fa-square-root-variable",     AppUrl = "/inventory/fiches",       		    ImgUrl = "fa-square-root-variable.jpg",      IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 2020, Code = "2020", Name = "Sayım Birleştirme",              Icon = "fa-solid fa-square-root-variable",     AppUrl = "/inventory/combining ",   		    ImgUrl = "fa-square-root-variable.jpg",      IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 2030, Code = "2030", Name = "Sayım Karşılaştırma",            Icon = "fa-solid fa-square-root-variable",     AppUrl = "/inventory/comparing",    		    ImgUrl = "fa-square-root-variable.jpg",      IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 2040, Code = "2040", Name = "Sayım Kesinleştirme",            Icon = "fa-solid fa-square-root-variable",     AppUrl = "/inventory/finalization", 		    ImgUrl = "fa-square-root-variable.jpg",      IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 2100, Code = "2100", Name = "Üretim İşlemleri",               Icon = "",                           		    AppUrl = "/production",                  	    ImgUrl = "",                   		         IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 2110, Code = "2110", Name = "Üretim Emri Başla/Bitir",        Icon = "fa-solid fa-gear",           		    AppUrl = "/production/prodorders",  		    ImgUrl = "fa-gear.jpg",           		     IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 2120, Code = "2120", Name = "Üretimde Harcananlar",           Icon = "fa-solid fa-user",           		    AppUrl = "/production/consumes",    		    ImgUrl = "fa-user.jpg",           		     IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 2130, Code = "2130", Name = "Üretilen Mallar",                Icon = "fa-solid fa-cubes",          		    AppUrl = "/production/prodentry",   		    ImgUrl = "fa-cubes.jpg",          		     IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 2140, Code = "2140", Name = "Hurdaya Ayırma",                 Icon = "fa-solid fa-dumpster",       		    AppUrl = "/production/approval",    		    ImgUrl = "fa-dumpster.jpg",       		     IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 2300, Code = "2300", Name = "Personel İşlemleri",             Icon = "",                           		    AppUrl = "/personnel",                   	    ImgUrl = "",                   		         IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 2310, Code = "2310", Name = "Avans Talepleri",                Icon = "fa-solid fa-gear",           		    AppUrl = "/personnel/advances",  			    ImgUrl = "fa-gear.jpg",           		     IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 2320, Code = "2320", Name = "İzin Talepleri",                 Icon = "fa-solid fa-user",           		    AppUrl = "/personnel/requests",    			    ImgUrl = "fa-user.jpg",           		     IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 2330, Code = "2330", Name = "Masraf Girişleri",               Icon = "fa-solid fa-cubes",          		    AppUrl = "/personnel/expenses",   			    ImgUrl = "fa-cubes.jpg",          		     IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 2340, Code = "2340", Name = "Yoklama",                        Icon = "fa-solid fa-dumpster",       		    AppUrl = "/personnel/checking",    			    ImgUrl = "fa-dumpster.jpg",                  IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 2400, Code = "2400", Name = "Kargo İşlemleri",                Icon = "",                                     AppUrl = "/eCargos",                  		    ImgUrl = "",                                 IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 2410, Code = "2410", Name = "Müşteriler",                     Icon = "fa-solid fa-users",                    AppUrl = "/eCargo/customers",       		    ImgUrl = "fa-users.jpg",                     IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 2420, Code = "2420", Name = "Taşıyıcılar",                    Icon = "fa-solid fa-truck-fast",               AppUrl = "/eCargo/carriers",        		    ImgUrl = "fa-truck-fast.jpg",                IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 2430, Code = "2430", Name = "Kargolar",                       Icon = "fa-solid fa-box-archive",              AppUrl = "/eCargo/cargomains",      		    ImgUrl = "fa-box-archive.jpg",               IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 2440, Code = "2440", Name = "Tahsilatlar",                    Icon = "fa-solid fa-wallet",                   AppUrl = "/eCargo/collects",        		    ImgUrl = "fa-wallet.jpg",                    IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 2450, Code = "2450", Name = "Ödemeler",                       Icon = "fa-solid fa-upload",                   AppUrl = "/eCargo/payments",        		    ImgUrl = "fa-upload.jpg",                    IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  },
                new Menu() { Ref = 2460, Code = "2460", Name = "Raporlar",                       Icon = "fa-solid fa-print",                    AppUrl = "/eCargo/reports",         		    ImgUrl = "fa-print.jpg",                     IsAdmin = false, Active = true, CreatedUser = 1, IsDeleted = false  }
                );

            /* Rites */
            int RiteRef = 0;
            builder.Entity<Rite>().HasData(
                new Rite { Ref = RiteRef+101, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1001, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1001	Ana Sayfa               */
                new Rite { Ref = RiteRef+102, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1100, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1100	Admin İşlemleri         */
                new Rite { Ref = RiteRef+103, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1110, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1110	Kullanıcılar            */
                new Rite { Ref = RiteRef+104, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1120, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1120	Firmalar                */
                new Rite { Ref = RiteRef+105, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1130, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1130	Roller                  */
                new Rite { Ref = RiteRef+106, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1140, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1140	Menuler                 */
                new Rite { Ref = RiteRef+107, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1200, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1200	Genel Tanımlar          */
                new Rite { Ref = RiteRef+108, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1210, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1210	Stok Birimleri          */
                new Rite { Ref = RiteRef+109, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1220, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1220	Stok Birim Setleri      */
                new Rite { Ref = RiteRef+110, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1230, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1230	Ülkeler                 */
                new Rite { Ref = RiteRef+111, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1240, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1240	Şehirler                */
                new Rite { Ref = RiteRef+112, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1250, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1250	Bankalar                */
                new Rite { Ref = RiteRef+113, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1260, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1260	Banka Şubeleri          */
                new Rite { Ref = RiteRef+114, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1300, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1300	Firma Tanımları         */
                new Rite { Ref = RiteRef+115, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1310, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1310	Personeller             */
                new Rite { Ref = RiteRef+116, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1320, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1320	Kasalar                 */
                new Rite { Ref = RiteRef+117, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1330, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1330	Banka Hesapları         */
                new Rite { Ref = RiteRef+118, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1340, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1340	Cariler                 */
                new Rite { Ref = RiteRef+119, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1350, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1350	Stoklar                 */
                new Rite { Ref = RiteRef+120, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1360, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1360	Fiyatlar                */
                new Rite { Ref = RiteRef+121, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1400, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1400	Kurs İşlemleri          */
                new Rite { Ref = RiteRef+122, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1410, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1410	Sınıflar                */
                new Rite { Ref = RiteRef+123, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1420, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1420	Kurslar                 */
                new Rite { Ref = RiteRef+124, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1430, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1430	Katılımcılar            */
                new Rite { Ref = RiteRef+125, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1440, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1440	Ortak Firmalar          */
                new Rite { Ref = RiteRef+126, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1450, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1450	Durum Kodları           */
                new Rite { Ref = RiteRef+127, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1460, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1460	Raporlar                */
                new Rite { Ref = RiteRef+128, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1500, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1500	Satış Öncesi            */
                new Rite { Ref = RiteRef+129, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1510, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1510	Adaylar                 */
                new Rite { Ref = RiteRef+130, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1520, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1520	Kişiler                 */
                new Rite { Ref = RiteRef+131, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1530, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1530	Faaliyetler             */
                new Rite { Ref = RiteRef+132, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1540, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1540	Teklifler               */
                new Rite { Ref = RiteRef+133, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1600, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1600	Satış İşlemleri         */
                new Rite { Ref = RiteRef+134, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1610, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1610	Siparişler              */
                new Rite { Ref = RiteRef+135, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1620, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1620	Sipariş Sevk            */
                new Rite { Ref = RiteRef+136, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1630, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1630	Toplu Mal Ayırma        */
                new Rite { Ref = RiteRef+137, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1640, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1640	Mal Teslim              */
                new Rite { Ref = RiteRef+138, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1700, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1700	Satın alma İşlemleri    */
                new Rite { Ref = RiteRef+139, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1710, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1710	Siparişler              */
                new Rite { Ref = RiteRef+140, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1720, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1720	Mal Kabul               */
                new Rite { Ref = RiteRef+141, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1730, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1730	Kalite kontrol          */
                new Rite { Ref = RiteRef+142, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1740, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1740	Kesin Kabul/Red         */
                new Rite { Ref = RiteRef+143, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1800, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1800	Satış Sonrası           */
                new Rite { Ref = RiteRef+144, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1810, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1810	Sozlesmeler             */
                new Rite { Ref = RiteRef+145, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1820, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1820	Bakımlar                */
                new Rite { Ref = RiteRef+146, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1830, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1830	Görevler                */
                new Rite { Ref = RiteRef+147, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1900, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1900	Ambar İşlemleri         */
                new Rite { Ref = RiteRef+148, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1910, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1910	Ambar Transfer          */
                new Rite { Ref = RiteRef+149, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 1920, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 1920	Adres/Raf Değiştirme    */
                new Rite { Ref = RiteRef+150, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 2000, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 2000	Sayım İşlemleri         */
                new Rite { Ref = RiteRef+151, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 2010, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 2010	Sayımlar                */
                new Rite { Ref = RiteRef+152, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 2020, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 2020	Sayım Birleştirme       */
                new Rite { Ref = RiteRef+153, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 2030, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 2030	Sayım Karşılaştırma     */
                new Rite { Ref = RiteRef+154, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 2040, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 2040	Sayım Kesinleştirme     */
                new Rite { Ref = RiteRef+155, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 2100, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 2100	Üretim İşlemleri        */
                new Rite { Ref = RiteRef+156, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 2110, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 2110	Üretim Emri Başla/Bitir */
                new Rite { Ref = RiteRef+157, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 2120, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 2120	Üretimde Harcananlar    */
                new Rite { Ref = RiteRef+158, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 2130, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 2130	Üretilen Mallar         */
                new Rite { Ref = RiteRef+159, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 2140, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 2140	Hurdaya Ayırma          */
                new Rite { Ref = RiteRef+160, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 2300, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 2300	Personel İşlemleri      */
                new Rite { Ref = RiteRef+161, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 2310, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 2310	Avans Talepleri         */
                new Rite { Ref = RiteRef+162, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 2320, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 2320	İzin Talepleri          */
                new Rite { Ref = RiteRef+163, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 2330, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 2330	Masraf Girişleri        */
                new Rite { Ref = RiteRef+164, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 2340, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 2340	Yoklama                 */
                new Rite { Ref = RiteRef+165, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 2400, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 2400	Kargo İşlemleri         */
                new Rite { Ref = RiteRef+166, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 2410, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 2410	Müşteriler              */
                new Rite { Ref = RiteRef+167, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 2420, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 2420	Taşıyıcılar             */
                new Rite { Ref = RiteRef+168, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 2430, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 2430	Kargolar                */
                new Rite { Ref = RiteRef+169, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 2440, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 2440	Tahsilatlar             */
                new Rite { Ref = RiteRef+170, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 2450, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 2450	Ödemeler                */
                new Rite { Ref = RiteRef+171, AppUserRef = 1, FirmRef = 1, RoleRef = 1, MenuRef = 2460, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 1) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 1) }, /* 2460	Raporlar                */

                new Rite { Ref = RiteRef+201, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1001, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1001	Ana Sayfa               */
                new Rite { Ref = RiteRef+202, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1100, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 0) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 0) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1100	Admin İşlemleri         */
                new Rite { Ref = RiteRef+203, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1110, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 0) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 0) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1110	Kullanıcılar            */
                new Rite { Ref = RiteRef+204, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1120, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 0) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 0) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1120	Firmalar                */
                new Rite { Ref = RiteRef+205, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1130, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 0) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 0) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1130	Roller                  */
                new Rite { Ref = RiteRef+206, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1140, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 0) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 0) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1140	Menuler                 */
                new Rite { Ref = RiteRef+207, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1200, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 0) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1200	Genel Tanımlar          */
                new Rite { Ref = RiteRef+208, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1210, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 0) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1210	Stok Birimleri          */
                new Rite { Ref = RiteRef+209, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1220, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 0) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1220	Stok Birim Setleri      */
                new Rite { Ref = RiteRef+210, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1230, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 0) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1230	Ülkeler                 */
                new Rite { Ref = RiteRef+211, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1240, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 0) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1240	Şehirler                */
                new Rite { Ref = RiteRef+212, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1250, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 0) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1250	Bankalar                */
                new Rite { Ref = RiteRef+213, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1260, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 0) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1260	Banka Şubeleri          */
                new Rite { Ref = RiteRef+214, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1300, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1300	Firma Tanımları         */
                new Rite { Ref = RiteRef+215, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1310, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1310	Personeller             */
                new Rite { Ref = RiteRef+216, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1320, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1320	Kasalar                 */
                new Rite { Ref = RiteRef+217, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1330, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1330	Banka Hesapları         */
                new Rite { Ref = RiteRef+218, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1340, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1340	Cariler                 */
                new Rite { Ref = RiteRef+219, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1350, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1350	Stoklar                 */
                new Rite { Ref = RiteRef+220, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1360, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1360	Fiyatlar                */
                new Rite { Ref = RiteRef+221, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1400, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1400	Kurs İşlemleri          */
                new Rite { Ref = RiteRef+222, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1410, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1410	Sınıflar                */
                new Rite { Ref = RiteRef+223, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1420, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1420	Kurslar                 */
                new Rite { Ref = RiteRef+224, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1430, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1430	Katılımcılar            */
                new Rite { Ref = RiteRef+225, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1440, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1440	Ortak Firmalar          */
                new Rite { Ref = RiteRef+226, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1450, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1450	Durum Kodları           */
                new Rite { Ref = RiteRef+227, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1460, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1460	Raporlar                */
                new Rite { Ref = RiteRef+228, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1500, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1500	Satış Öncesi            */
                new Rite { Ref = RiteRef+229, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1510, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1510	Adaylar                 */
                new Rite { Ref = RiteRef+230, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1520, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1520	Kişiler                 */
                new Rite { Ref = RiteRef+231, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1530, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1530	Faaliyetler             */
                new Rite { Ref = RiteRef+232, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1540, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1540	Teklifler               */
                new Rite { Ref = RiteRef+233, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1600, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1600	Satış İşlemleri         */
                new Rite { Ref = RiteRef+234, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1610, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1610	Siparişler              */
                new Rite { Ref = RiteRef+235, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1620, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1620	Sipariş Sevk            */
                new Rite { Ref = RiteRef+236, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1630, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1630	Toplu Mal Ayırma        */
                new Rite { Ref = RiteRef+237, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1640, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1640	Mal Teslim              */
                new Rite { Ref = RiteRef+238, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1700, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1700	Satın alma İşlemleri    */
                new Rite { Ref = RiteRef+239, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1710, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1710	Siparişler              */
                new Rite { Ref = RiteRef+240, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1720, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1720	Mal Kabul               */
                new Rite { Ref = RiteRef+241, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1730, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1730	Kalite kontrol          */
                new Rite { Ref = RiteRef+242, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1740, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1740	Kesin Kabul/Red         */
                new Rite { Ref = RiteRef+243, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1800, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1800	Satış Sonrası           */
                new Rite { Ref = RiteRef+244, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1810, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1810	Sozlesmeler             */
                new Rite { Ref = RiteRef+245, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1820, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1820	Bakımlar                */
                new Rite { Ref = RiteRef+246, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1830, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1830	Görevler                */
                new Rite { Ref = RiteRef+247, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1900, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1900	Ambar İşlemleri         */
                new Rite { Ref = RiteRef+248, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1910, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1910	Ambar Transfer          */
                new Rite { Ref = RiteRef+249, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 1920, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 1920	Adres/Raf Değiştirme    */
                new Rite { Ref = RiteRef+250, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 2000, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 2000	Sayım İşlemleri         */
                new Rite { Ref = RiteRef+251, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 2010, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 2010	Sayımlar                */
                new Rite { Ref = RiteRef+252, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 2020, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 2020	Sayım Birleştirme       */
                new Rite { Ref = RiteRef+253, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 2030, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 2030	Sayım Karşılaştırma     */
                new Rite { Ref = RiteRef+254, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 2040, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 2040	Sayım Kesinleştirme     */
                new Rite { Ref = RiteRef+255, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 2100, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 2100	Üretim İşlemleri        */
                new Rite { Ref = RiteRef+256, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 2110, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 2110	Üretim Emri Başla/Bitir */
                new Rite { Ref = RiteRef+257, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 2120, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 2120	Üretimde Harcananlar    */
                new Rite { Ref = RiteRef+258, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 2130, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 2130	Üretilen Mallar         */
                new Rite { Ref = RiteRef+259, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 2140, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 2140	Hurdaya Ayırma          */
                new Rite { Ref = RiteRef+260, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 2300, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 2300	Personel İşlemleri      */
                new Rite { Ref = RiteRef+261, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 2310, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 2310	Avans Talepleri         */
                new Rite { Ref = RiteRef+262, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 2320, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 2320	İzin Talepleri          */
                new Rite { Ref = RiteRef+263, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 2330, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 2330	Masraf Girişleri        */
                new Rite { Ref = RiteRef+264, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 2340, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 2340	Yoklama                 */
                new Rite { Ref = RiteRef+265, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 2400, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 2400	Kargo İşlemleri         */
                new Rite { Ref = RiteRef+266, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 2410, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 2410	Müşteriler              */
                new Rite { Ref = RiteRef+267, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 2420, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 2420	Taşıyıcılar             */
                new Rite { Ref = RiteRef+268, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 2430, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 2430	Kargolar                */
                new Rite { Ref = RiteRef+269, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 2440, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 2440	Tahsilatlar             */
                new Rite { Ref = RiteRef+270, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 2450, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }, /* 2450	Ödemeler                */
                new Rite { Ref = RiteRef+271, AppUserRef = 2, FirmRef = 1, RoleRef = 1, MenuRef = 2460, BttnRef = (ButtonTypeEnum.CREATE * 1) + (ButtonTypeEnum.SELECT * 1) + (ButtonTypeEnum.UPDATE * 1) + (ButtonTypeEnum.DELETE * 0) + (ButtonTypeEnum.EXCEPT * 1) + (ButtonTypeEnum.MIGRATE * 0) }  /* 2460	Raporlar                */

                );

            /* Ülkeler */
            int CountryRef = 0;
            builder.Entity<Country>().HasData(
                new Country() { Ref = CountryRef+101, Code3 = "TUR", Code2 = "TR", ShortNameTrk = "Türkiye", ShortNameEng = "Türkiye", OfficialNameTrk = "Türkiye Cumhuriyeti"        , OfficialNameEng = "Republic of Türkiye"     , PhoneAreaCode = "90", CustomAreaCode = "52" , CurrencyCode = "TL" , Active = true, CreatedUser = 1, IsDeleted = false },
                new Country() { Ref = CountryRef+102, Code3 = "USA", Code2 = "US", ShortNameTrk = "A.B.D." , ShortNameEng = "U.S.A." , OfficialNameTrk = "Amerika Birleşik Devletleri", OfficialNameEng = "United States of America", PhoneAreaCode = "1" , CustomAreaCode = "400", CurrencyCode = "USD", Active = true, CreatedUser = 1, IsDeleted = false }
                );

            /* Şehirler */
            int CityRef = 0;
            builder.Entity<City>().HasData(
                new City() { Ref = CityRef + 101, Code3 = "ADA", Code2 = "01", NameTrk = "Adana     ", NameEng = "Adana       ", PhoneAreaCode = "322", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 102, Code3 = "ADI", Code2 = "02", NameTrk = "Adıyaman  ", NameEng = "Adıyaman    ", PhoneAreaCode = "416", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 103, Code3 = "AFY", Code2 = "03", NameTrk = "Afyon     ", NameEng = "Afyon       ", PhoneAreaCode = "272", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 104, Code3 = "AGR", Code2 = "04", NameTrk = "Ağrı      ", NameEng = "Ağrı        ", PhoneAreaCode = "472", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 168, Code3 = "AKS", Code2 = "68", NameTrk = "Aksaray   ", NameEng = "Aksaray     ", PhoneAreaCode = "382", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 105, Code3 = "AMA", Code2 = "05", NameTrk = "Amasya    ", NameEng = "Amasya      ", PhoneAreaCode = "358", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 106, Code3 = "ANK", Code2 = "06", NameTrk = "Ankara    ", NameEng = "Ankara      ", PhoneAreaCode = "312", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 107, Code3 = "ANT", Code2 = "07", NameTrk = "Antalya   ", NameEng = "Antalya     ", PhoneAreaCode = "242", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 175, Code3 = "ARD", Code2 = "75", NameTrk = "Ardahan   ", NameEng = "Ardahan     ", PhoneAreaCode = "478", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 108, Code3 = "ART", Code2 = "08", NameTrk = "Artvin    ", NameEng = "Artvin      ", PhoneAreaCode = "466", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 109, Code3 = "AYD", Code2 = "09", NameTrk = "Aydın     ", NameEng = "Aydın       ", PhoneAreaCode = "256", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 110, Code3 = "BAL", Code2 = "10", NameTrk = "Balıkesir ", NameEng = "Balıkesir   ", PhoneAreaCode = "266", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 174, Code3 = "BAR", Code2 = "74", NameTrk = "Bartın    ", NameEng = "Bartın      ", PhoneAreaCode = "378", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 172, Code3 = "BAT", Code2 = "72", NameTrk = "Batman    ", NameEng = "Batman      ", PhoneAreaCode = "488", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 169, Code3 = "BAY", Code2 = "69", NameTrk = "Bayburt   ", NameEng = "Bayburt     ", PhoneAreaCode = "458", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 111, Code3 = "BIL", Code2 = "11", NameTrk = "Bilecik   ", NameEng = "Bilecik     ", PhoneAreaCode = "228", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 112, Code3 = "BIN", Code2 = "12", NameTrk = "Bingöl    ", NameEng = "Bingöl      ", PhoneAreaCode = "426", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 113, Code3 = "BIT", Code2 = "13", NameTrk = "Bitlis    ", NameEng = "Bitlis      ", PhoneAreaCode = "434", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 114, Code3 = "BOL", Code2 = "14", NameTrk = "Bolu      ", NameEng = "Bolu        ", PhoneAreaCode = "374", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 115, Code3 = "BRD", Code2 = "15", NameTrk = "Burdur    ", NameEng = "Burdur      ", PhoneAreaCode = "248", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 116, Code3 = "BRS", Code2 = "16", NameTrk = "Bursa     ", NameEng = "Bursa       ", PhoneAreaCode = "224", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 117, Code3 = "CAN", Code2 = "17", NameTrk = "Çanakkale ", NameEng = "Çanakkale   ", PhoneAreaCode = "286", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 118, Code3 = "CNR", Code2 = "18", NameTrk = "Çankırı   ", NameEng = "Çankırı     ", PhoneAreaCode = "376", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 119, Code3 = "COR", Code2 = "19", NameTrk = "Çorum     ", NameEng = "Çorum       ", PhoneAreaCode = "364", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 120, Code3 = "DEN", Code2 = "20", NameTrk = "Denizli   ", NameEng = "Denizli     ", PhoneAreaCode = "258", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 121, Code3 = "DIY", Code2 = "21", NameTrk = "Diyarbakır", NameEng = "Diyarbakır  ", PhoneAreaCode = "412", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 181, Code3 = "DUZ", Code2 = "81", NameTrk = "Düzce     ", NameEng = "Düzce       ", PhoneAreaCode = "380", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 122, Code3 = "EDI", Code2 = "22", NameTrk = "Edirne    ", NameEng = "Edirne      ", PhoneAreaCode = "284", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 123, Code3 = "ELA", Code2 = "23", NameTrk = "Elazığ    ", NameEng = "Elazığ      ", PhoneAreaCode = "424", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 124, Code3 = "ERC", Code2 = "24", NameTrk = "Erzincan  ", NameEng = "Erzincan    ", PhoneAreaCode = "446", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 125, Code3 = "ERZ", Code2 = "25", NameTrk = "Erzurum   ", NameEng = "Erzurum     ", PhoneAreaCode = "442", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 126, Code3 = "ESK", Code2 = "26", NameTrk = "Eskişehir ", NameEng = "Eskişehir   ", PhoneAreaCode = "222", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 127, Code3 = "GAZ", Code2 = "27", NameTrk = "Gaziantep ", NameEng = "Gaziantep   ", PhoneAreaCode = "342", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 128, Code3 = "GIR", Code2 = "28", NameTrk = "Giresun   ", NameEng = "Giresun     ", PhoneAreaCode = "454", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 129, Code3 = "GUM", Code2 = "29", NameTrk = "Gümüşhane ", NameEng = "Gümüşhane   ", PhoneAreaCode = "456", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 130, Code3 = "HAK", Code2 = "30", NameTrk = "Hakkari   ", NameEng = "Hakkari     ", PhoneAreaCode = "438", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 131, Code3 = "HAT", Code2 = "31", NameTrk = "Hatay     ", NameEng = "Hatay       ", PhoneAreaCode = "326", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 176, Code3 = "IGD", Code2 = "76", NameTrk = "Iğdır     ", NameEng = "Iğdır       ", PhoneAreaCode = "476", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 132, Code3 = "ISP", Code2 = "32", NameTrk = "Isparta   ", NameEng = "Isparta     ", PhoneAreaCode = "246", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 134, Code3 = "IST", Code2 = "34", NameTrk = "İstanbul  ", NameEng = "İstanbul    ", PhoneAreaCode = "212", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 135, Code3 = "IZM", Code2 = "35", NameTrk = "İzmir     ", NameEng = "İzmir       ", PhoneAreaCode = "232", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 146, Code3 = "KAH", Code2 = "46", NameTrk = "K.Maraş   ", NameEng = "K.Maraş     ", PhoneAreaCode = "344", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 136, Code3 = "KRS", Code2 = "36", NameTrk = "Kars      ", NameEng = "Kars        ", PhoneAreaCode = "474", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 170, Code3 = "KRM", Code2 = "70", NameTrk = "Karaman   ", NameEng = "Karaman     ", PhoneAreaCode = "338", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 178, Code3 = "KRB", Code2 = "78", NameTrk = "Karabük   ", NameEng = "Karabük     ", PhoneAreaCode = "370", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 137, Code3 = "KAS", Code2 = "37", NameTrk = "Kastamonu ", NameEng = "Kastamonu   ", PhoneAreaCode = "366", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 138, Code3 = "KAY", Code2 = "38", NameTrk = "Kayseri   ", NameEng = "Kayseri     ", PhoneAreaCode = "352", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 171, Code3 = "KKL", Code2 = "71", NameTrk = "Kırıkkale ", NameEng = "Kırıkkale   ", PhoneAreaCode = "318", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 179, Code3 = "KIL", Code2 = "79", NameTrk = "Kilis     ", NameEng = "Kilis       ", PhoneAreaCode = "348", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 141, Code3 = "KOC", Code2 = "41", NameTrk = "Kocaeli   ", NameEng = "Kocaeli     ", PhoneAreaCode = "262", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 142, Code3 = "KON", Code2 = "42", NameTrk = "Konya     ", NameEng = "Konya       ", PhoneAreaCode = "332", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 139, Code3 = "KRK", Code2 = "39", NameTrk = "Kırklareli", NameEng = "Kırklareli  ", PhoneAreaCode = "288", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 140, Code3 = "KSH", Code2 = "40", NameTrk = "Kırşehir  ", NameEng = "Kırşehir    ", PhoneAreaCode = "386", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 143, Code3 = "KUT", Code2 = "43", NameTrk = "Kütahya   ", NameEng = "Kütahya     ", PhoneAreaCode = "274", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 144, Code3 = "MAL", Code2 = "44", NameTrk = "Malatya   ", NameEng = "Malatya     ", PhoneAreaCode = "422", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 145, Code3 = "MAN", Code2 = "45", NameTrk = "Manisa    ", NameEng = "Manisa      ", PhoneAreaCode = "236", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 147, Code3 = "MAR", Code2 = "47", NameTrk = "Mardin    ", NameEng = "Mardin      ", PhoneAreaCode = "482", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 133, Code3 = "MER", Code2 = "33", NameTrk = "Mersin    ", NameEng = "Mersin      ", PhoneAreaCode = "324", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 148, Code3 = "MUG", Code2 = "48", NameTrk = "Muğla     ", NameEng = "Muğla       ", PhoneAreaCode = "252", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 149, Code3 = "MUS", Code2 = "49", NameTrk = "Muş       ", NameEng = "Muş         ", PhoneAreaCode = "436", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 150, Code3 = "NEV", Code2 = "50", NameTrk = "Nevşehir  ", NameEng = "Nevşehir    ", PhoneAreaCode = "384", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 151, Code3 = "NIG", Code2 = "51", NameTrk = "Niğde     ", NameEng = "Niğde       ", PhoneAreaCode = "388", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 152, Code3 = "ORD", Code2 = "52", NameTrk = "Ordu      ", NameEng = "Ordu        ", PhoneAreaCode = "452", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 180, Code3 = "OSM", Code2 = "80", NameTrk = "Osmaniye  ", NameEng = "Osmaniye    ", PhoneAreaCode = "328", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 153, Code3 = "RIZ", Code2 = "53", NameTrk = "Rize      ", NameEng = "Rize        ", PhoneAreaCode = "464", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 154, Code3 = "SAK", Code2 = "54", NameTrk = "Sakarya   ", NameEng = "Sakarya     ", PhoneAreaCode = "264", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 155, Code3 = "SAM", Code2 = "55", NameTrk = "Samsun    ", NameEng = "Samsun      ", PhoneAreaCode = "362", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 156, Code3 = "SII", Code2 = "56", NameTrk = "Siirt     ", NameEng = "Siirt       ", PhoneAreaCode = "484", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 157, Code3 = "SIN", Code2 = "57", NameTrk = "Sinop     ", NameEng = "Sinop       ", PhoneAreaCode = "368", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 158, Code3 = "SIV", Code2 = "58", NameTrk = "Sivas     ", NameEng = "Sivas       ", PhoneAreaCode = "346", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 163, Code3 = "SUR", Code2 = "63", NameTrk = "Şanlıurfa ", NameEng = "Şanlıurfa   ", PhoneAreaCode = "414", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 173, Code3 = "SIR", Code2 = "73", NameTrk = "Şırnak    ", NameEng = "Şırnak      ", PhoneAreaCode = "486", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 159, Code3 = "TEK", Code2 = "59", NameTrk = "Tekirdağ  ", NameEng = "Tekirdağ    ", PhoneAreaCode = "282", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 160, Code3 = "TOK", Code2 = "60", NameTrk = "Tokat     ", NameEng = "Tokat       ", PhoneAreaCode = "356", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 161, Code3 = "TRA", Code2 = "61", NameTrk = "Trabzon   ", NameEng = "Trabzon     ", PhoneAreaCode = "462", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 162, Code3 = "TUN", Code2 = "62", NameTrk = "Tunceli   ", NameEng = "Tunceli     ", PhoneAreaCode = "428", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 164, Code3 = "USK", Code2 = "64", NameTrk = "Uşak      ", NameEng = "Uşak        ", PhoneAreaCode = "276", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 165, Code3 = "VAN", Code2 = "65", NameTrk = "Van       ", NameEng = "Van         ", PhoneAreaCode = "432", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 177, Code3 = "YAL", Code2 = "77", NameTrk = "Yalova    ", NameEng = "Yalova      ", PhoneAreaCode = "226", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 166, Code3 = "YOZ", Code2 = "66", NameTrk = "Yozgat    ", NameEng = "Yozgat      ", PhoneAreaCode = "354", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false },
                new City() { Ref = CityRef + 167, Code3 = "ZON", Code2 = "67", NameTrk = "Zonguldak ", NameEng = "Zonguldak   ", PhoneAreaCode = "372", CountryCode = "TUR", Active = true, CreatedUser = 1, IsDeleted = false }


                );

            /* Birimler */
            int UnitRef = 0;
            builder.Entity<StkUnit>().HasData(
                new StkUnit() { Ref = UnitRef+101, Code = "AD", Name = "Adet"      , UnitType = StkUnitTypeEnum.MIKTAR , Active = true, CreatedUser = 1, IsDeleted = false },
                new StkUnit() { Ref = UnitRef+102, Code = "PK", Name = "Paket"     , UnitType = StkUnitTypeEnum.MIKTAR , Active = true, CreatedUser = 1, IsDeleted = false },
                new StkUnit() { Ref = UnitRef+103, Code = "KL", Name = "Koli"      , UnitType = StkUnitTypeEnum.MIKTAR , Active = true, CreatedUser = 1, IsDeleted = false },
                new StkUnit() { Ref = UnitRef+104, Code = "PL", Name = "Palet"     , UnitType = StkUnitTypeEnum.MIKTAR , Active = true, CreatedUser = 1, IsDeleted = false },
                new StkUnit() { Ref = UnitRef+105, Code = "GR", Name = "Gram"      , UnitType = StkUnitTypeEnum.AGIRLIK, Active = true, CreatedUser = 1, IsDeleted = false },
                new StkUnit() { Ref = UnitRef+106, Code = "KG", Name = "Kilogram"  , UnitType = StkUnitTypeEnum.AGIRLIK, Active = true, CreatedUser = 1, IsDeleted = false },
                new StkUnit() { Ref = UnitRef+107, Code = "TN", Name = "Ton"       , UnitType = StkUnitTypeEnum.AGIRLIK, Active = true, CreatedUser = 1, IsDeleted = false },
                new StkUnit() { Ref = UnitRef+108, Code = "ML", Name = "MiliLitre" , UnitType = StkUnitTypeEnum.HACIM  , Active = true, CreatedUser = 1, IsDeleted = false },
                new StkUnit() { Ref = UnitRef+109, Code = "LT", Name = "Litre"     , UnitType = StkUnitTypeEnum.HACIM  , Active = true, CreatedUser = 1, IsDeleted = false }
                );

            /* Birim Setleri */
            int UnitSetRef = 0;
            builder.Entity<StkUnitSet>().HasData(
                new StkUnitSet()
                {
                    Ref = UnitSetRef+101,
                    Code = "AD-PK-KL-PL",
                    Name = "Adet-Paket-Koli-Palet",
                    Active = true,
                    CreatedUser = 1,
                    IsDeleted = false,
                    //Units = { new StkUnit() { Ref = 1 }, new StkUnit() { Ref = 2 }, new StkUnit() { Ref = 3 } }
                },
                new StkUnitSet()
                {
                    Ref = UnitSetRef+102,
                    Code = "GR-KG-TN",
                    Name = "Gram-Kilogram-Ton",
                    Active = true,
                    CreatedUser = 1,
                    IsDeleted = false,
                    //Units = { new StkUnit() { Ref = 4 }, new StkUnit() { Ref = 5 } }
                },
                new StkUnitSet()
                {
                    Ref = UnitSetRef+103,
                    Code = "ML-LT",
                    Name = "Mililitre-Litre",
                    Active = true,
                    CreatedUser = 1,
                    IsDeleted = false,
                    //Units = { new StkUnit() { Ref = 7 }, new StkUnit() { Ref = 8 } }
                    }
                );

        }

    }
}
